# ssh, https
git_protocol: ssh

# Editor for issues, PRs, etc.
editor: positron

# enabled, disabled (global, not per-hostname)
prompt: enabled

# Pager for output (cat to disable)
pager: less

# Aliases
aliases:
    co: pr checkout
    prm: pr merge --squash --delete-branch

# Unix socket for HTTP
http_unix_socket:

# Web browser
browser:

version: "1"
