user_pref("extensions.zotero.dataDir", "/home/julien/Zotero");
user_pref("extensions.zotero.useDataDir", true);

user_pref("intl.accept_languages", "fr, fr-fr, en-us, en");
user_pref("extensions.zotero.fontSize", "1.08");
user_pref("extensions.zotero.note.fontSize", "12");
user_pref("extensions.zotero.reader.contentDarkMode", false);
user_pref("extensions.zotero.reader.darkTheme", "false");
user_pref("extensions.zotero.recursiveCollections", true);
user_pref("extensions.zotero.search.quicksearch-mode", "everything");
user_pref("extensions.zotero.tagSelector.showAutomatic", false);

user_pref("extensions.zotero.httpServer.localAPI.enabled", true);

user_pref("extensions.zotero.cite.automaticJournalAbbreviations", false);
user_pref("extensions.zotero.export.quickCopy.setting", "export=b6e39b57-8942-4d11-8259-342c46ce395f");
user_pref("extensions.zotero.import.createCollection", false);
user_pref("extensions.zotero.import.fileHandling", "store");
user_pref("extensions.zotero.sync.storage.groups.enabled", false);

user_pref("extensions.zotero.translators.better-bibtex.citekeyFormat", "auth.lower + year");
user_pref("extensions.zotero.translators.better-bibtex.fillKeyAfter", 1);

user_pref("extensions.zotero.findPDFs.resolvers", "[{\"name\":\"Sci-Hub\",\"method\":\"GET\",\"url\":\"https://sci-hub.al/{doi}\",\"mode\":\"html\",\"selector\":\"#pdf\",\"attribute\":\"src\",\"automatic\":true},{\"name\":\"Sci-Hub\",\"method\":\"GET\",\"url\":\"https://sci-hub.mk/{doi}\",\"mode\":\"html\",\"selector\":\"#pdf\",\"attribute\":\"src\",\"automatic\":true},{\"name\":\"Sci-Hub\",\"method\":\"GET\",\"url\":\"https://sci-hub.ee/{doi}\",\"mode\":\"html\",\"selector\":\"#pdf\",\"attribute\":\"src\",\"automatic\":true},{\"name\":\"Sci-Hub\",\"method\":\"GET\",\"url\":\"https://sci-hub.vg/{doi}\",\"mode\":\"html\",\"selector\":\"#pdf\",\"attribute\":\"src\",\"automatic\":true},{\"name\":\"Sci-Hub\",\"method\":\"GET\",\"url\":\"https://sci-hub.fr/{doi}\",\"mode\":\"html\",\"selector\":\"#pdf\",\"attribute\":\"src\",\"automatic\":true},{\"name\":\"Sci-Hub\",\"method\":\"GET\",\"url\":\"https://sci-hub.st/{doi}\",\"mode\":\"html\",\"selector\":\"#pdf\",\"attribute\":\"src\",\"automatic\":true},{\"name\":\"Sci-Hub\",\"method\":\"GET\",\"url\":\"https://sci-hub.mobi/{doi}\",\"mode\":\"html\",\"selector\":\"#pdf\",\"attribute\":\"src\",\"automatic\":true},{\"name\":\"Sci-Hub\",\"method\":\"GET\",\"url\":\"https://sci-hub.run/{doi}\",\"mode\":\"html\",\"selector\":\"#pdf\",\"attribute\":\"src\",\"automatic\":true},{\"name\":\"Sci-Hub\",\"method\":\"GET\",\"url\":\"https://sci-hub.se/{doi}\",\"mode\":\"html\",\"selector\":\"#pdf\",\"attribute\":\"src\",\"automatic\":true},{\"name\":\"Sci-Hub\",\"method\":\"GET\",\"url\":\"https://sci-hub.ru/{doi}\",\"mode\":\"html\",\"selector\":\"#pdf\",\"attribute\":\"src\",\"automatic\":true},{\"name\":\"Sci-Hub\",\"method\":\"GET\",\"url\":\"https://sci-hub.box/{doi}\",\"mode\":\"html\",\"selector\":\"#pdf\",\"attribute\":\"src\",\"automatic\":true},{\"name\":\"Sci-Hub\",\"method\":\"GET\",\"url\":\"https://sci-hub.red/{doi}\",\"mode\":\"html\",\"selector\":\"#pdf\",\"attribute\":\"src\",\"automatic\":true},{\"name\":\"Sci-Hub\",\"method\":\"GET\",\"url\":\"https://sci-hub.ren/{doi}\",\"mode\":\"html\",\"selector\":\"#pdf\",\"attribute\":\"src\",\"automatic\":true}]");
user_pref("extensions.zotero.scipdfresolvers", "[{\"name\":\"Sci-Hub\",\"method\":\"GET\",\"url\":\"https://sci-hub.al/{doi}\",\"mode\":\"html\",\"selector\":\"#pdf\",\"attribute\":\"src\",\"automatic\":true},{\"name\":\"Sci-Hub\",\"method\":\"GET\",\"url\":\"https://sci-hub.mk/{doi}\",\"mode\":\"html\",\"selector\":\"#pdf\",\"attribute\":\"src\",\"automatic\":true},{\"name\":\"Sci-Hub\",\"method\":\"GET\",\"url\":\"https://sci-hub.ee/{doi}\",\"mode\":\"html\",\"selector\":\"#pdf\",\"attribute\":\"src\",\"automatic\":true},{\"name\":\"Sci-Hub\",\"method\":\"GET\",\"url\":\"https://sci-hub.vg/{doi}\",\"mode\":\"html\",\"selector\":\"#pdf\",\"attribute\":\"src\",\"automatic\":true},{\"name\":\"Sci-Hub\",\"method\":\"GET\",\"url\":\"https://sci-hub.fr/{doi}\",\"mode\":\"html\",\"selector\":\"#pdf\",\"attribute\":\"src\",\"automatic\":true},{\"name\":\"Sci-Hub\",\"method\":\"GET\",\"url\":\"https://sci-hub.st/{doi}\",\"mode\":\"html\",\"selector\":\"#pdf\",\"attribute\":\"src\",\"automatic\":true},{\"name\":\"Sci-Hub\",\"method\":\"GET\",\"url\":\"https://sci-hub.mobi/{doi}\",\"mode\":\"html\",\"selector\":\"#pdf\",\"attribute\":\"src\",\"automatic\":true},{\"name\":\"Sci-Hub\",\"method\":\"GET\",\"url\":\"https://sci-hub.run/{doi}\",\"mode\":\"html\",\"selector\":\"#pdf\",\"attribute\":\"src\",\"automatic\":true},{\"name\":\"Sci-Hub\",\"method\":\"GET\",\"url\":\"https://sci-hub.se/{doi}\",\"mode\":\"html\",\"selector\":\"#pdf\",\"attribute\":\"src\",\"automatic\":true},{\"name\":\"Sci-Hub\",\"method\":\"GET\",\"url\":\"https://sci-hub.ru/{doi}\",\"mode\":\"html\",\"selector\":\"#pdf\",\"attribute\":\"src\",\"automatic\":true},{\"name\":\"Sci-Hub\",\"method\":\"GET\",\"url\":\"https://sci-hub.box/{doi}\",\"mode\":\"html\",\"selector\":\"#pdf\",\"attribute\":\"src\",\"automatic\":true},{\"name\":\"Sci-Hub\",\"method\":\"GET\",\"url\":\"https://sci-hub.red/{doi}\",\"mode\":\"html\",\"selector\":\"#pdf\",\"attribute\":\"src\",\"automatic\":true},{\"name\":\"Sci-Hub\",\"method\":\"GET\",\"url\":\"https://sci-hub.ren/{doi}\",\"mode\":\"html\",\"selector\":\"#pdf\",\"attribute\":\"src\",\"automatic\":true}]");
user_pref("userCustomResolvers", "[\"resolvers\"]");
