#:schema https://panache.bz/panache.schema.json

flavor = "quarto"

extend-exclude = [
  ".quarto/**",
  "_extensions/**",
  "tests/testthat/_snaps/",
  "**/.claude/**",
]

[format]
line-width = 80
wrap = "semantic"
math-delimiter-style = "preserve"

[formatters]
r = "air"
python = "ruff"

[linters]
r = "jarl"
python = "ruff"
